import './globals.css';
import { type Metadata } from 'next';
import { Mulish } from 'next/font/google';
import { cn } from '@/lib/utils';
import Header from '@/components/Header';
import { Toaster } from '@/components/ui/toaster';
import { SpeedInsights } from '@vercel/speed-insights/next';
import { ReactNode } from 'react';
import Provider from '@/provider';

const mulish = Mulish({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(mulish.className, 'min-h-screen bg-background')}>
        <Provider>
          <Header />
          <div className="m-auto max-w-[1336px]">{children}</div>
          <Toaster />
        </Provider>
        <SpeedInsights />
      </body>
    </html>
  );
}
